export const ROUTES = {
  HOME: '/',
  RESTAURANTS: '/restaurants',
  RESTAURANT_DETAIL: '/restaurants/:id',
  CART: '/cart',
  CHECKOUT: '/checkout',
  CHECKOUT_RESTAURANT: '/checkout/restaurant/:restaurantId',
  CHECKOUT_REVIEW: '/checkout/review',
  SUCCESS: '/success',
  ORDERS: '/orders',
  FAVORITES: '/favorites',
  ABOUT: '/about',
  CONTACT: '/contact',
  PRIVACY: '/privacy',
  TERMS: '/terms',
};
